name: 'SimpleLocalize'
description: 'Manage localization files with SimpleLocalize Github Action'
author: "SimpleLocalize"
branding:
  icon: 'download-cloud'
  color: 'blue'
inputs:
  command:
    description: 'Choose a command'
    required: true
    default: 'status'
  cli-version:
    description: 'Choose a command'
    required: true
    default: 'status'
  api-key:
    description: 'Project API Key'
    required: false
    default: ''
  download-path:
    description: 'Where files should be downloaded'
    required: false
    default: './messages.json'
  download-format:
    description: 'Choose a localization files format'
    required: false
    default: 'multi-language-json'
  download-options:
    description: 'Choose additional download options'
    required: false
    default: ''
  upload-path:
    description: 'Which files should be uploaded'
    required: false
    default: './messages.json'
  upload-format:
    description: 'Choose a localization files format'
    required: false
    default: 'multi-language-json'
  upload-options:
    description: 'Choose additional upload options'
    required: false
    default: ''
  customer-ids:
    description: 'Download translations for given customerIds'
    required: false
    default: ''
  args:
    description: 'Additional arguments'
    required: false
    default: ''
runs:
  using: 'composite'
  steps:
    - name: "Print inputs"
      run: |
        echo "Test SimpleLocalize"
        echo "command: ${{ inputs.command }}"
        echo "cli-version: ${{ inputs.cli-version }}"
        if [ -z "${{ inputs.api-key }}" ]; then
          echo "api-key: [empty]"
        else
          echo "api-key: [hidden]"
        fi
        echo "download-path: ${{ inputs.download-path }}"
        echo "download-format: ${{ inputs.download-format }}"
        echo "upload-path: ${{ inputs.upload-path }}"
        echo "upload-format: ${{ inputs.upload-format }}"
        echo "args: ${{ inputs.args }}"
      shell: bash
    - name: "Setup Java"
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '20'
    - name: "Download SimpleLocalize CLI"
      run: "curl -o simplelocalize.jar https://get.simplelocalize.io/binaries/${{ inputs.cli-version }}/simplelocalize-cli-${{ inputs.cli-version }}.jar"
      shell: bash
    - name: "Execute SimpleLocalize CLI Command"
      run: |
          java -jar simplelocalize.jar ${{ inputs.command }} ${{ inputs.args }}
      shell: bash

